### ISSUE TITLE
Auto start search

### ISSUE THREAD

**Issue by Walner92** [swissspidy/voice-search#26]
Hello Pascal Birchler, my name is Eugene, I'm from Ukraine and I really liked your Voice Search v 1.2.1 plugin. I would like to ask you for help to tell me where it is possible to change a part of the code so that when a voice request starts an automatic search without pressing the enter key, or perhaps add such a function in the next update, it saves time and is very convenient. I hope I did not bother you too much with this request, and thank you again for such a plugin.
I apologize for the inaccurate text translated via google translator.

**Comment by swissspidy** [comment]
Great suggestion, thank you!

I will add this.

**Comment by swissspidy** [comment]
I just published version 1.4.0 with this enhancement.

Thanks again for your suggestion.
