### ISSUE TITLE
well....

### ISSUE THREAD

**Issue by BurlesonBrad** [swissspidy/voice-search#4]
...the only problem I had was that I couldn't get it to fire on https://pressily.com  

Ideally, someday, I'll have a bazillion step-by-step video tutorials on plugins, WooCommerce, EDD, AffiliateWP, and more! But for now I was just _playing_ on it :wink: 

In the left sidebar is the plugin and the search widget.  When I saw it wasn't working, _(and since it wasn't really a priority, just a "cool factor")_, I just simply moved on.

God only knows what I've done with all my pjax, php7, cache, more cache, and tweaks to break the voice search, but.... it ain't workin' last time I checked.

@swissspidy Do you see anything off the top-of-your head that'd break it?  I'll #always-be-learning, but sometimes some a y'all rocket geniuses start mixing up all the programming languages and I get a bit wonky on trying to debug things.

```
### Begin System Info ###

	** WORDPRESS DATA **
Multisite:				No
SITE_URL:				https://pressily.com
HOME_URL:				https://pressily.com
WP Version:				4.5.3
Permalink:				/%postname%/
Cur Theme:				Storefront 2.0.5
Post Types:				post, page, attachment, revision, nav_menu_item, async-scan-result, scanresult, note, mc4wp-form, boxzilla-box, course, lesson, quiz, question, multiple_question, sensei_message, certificate, certificate_template
Post Stati:				publish, future, draft, pending, private, trash, auto-draft, inherit
User Count:				11

	** WORDPRESS CONFIG **
WP_DEBUG:				Disabled
WP Memory Limit:			40MB
Table Prefix:				*****
Prefix Length:				Acceptable (5 characters)
Show On Front:				page
Page On Front:				Home (ID# 1569)
Page For Posts:				 (ID# 0)

	** BROWSER DATA **
Platform:				Windows
Browser Name				Chrome
Browser Version:				51.0.2704.103
Browser User Agent:			Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

	** SERVER DATA **
jQuery Version				1.12.4
PHP Version:				7.0.8
MySQL Version:				5.5.5
Server Software:				LiteSpeed

	** PHP CONFIGURATION **
Safe Mode:				No
Memory Limit:				256M
Upload Max:				128M
Post Max:				128M
Time Limit:				300
Max Input Vars:				1000
Display Errors:				Off
Sessions:				Disabled
Session Name:				PHPSESSID
Cookie Path:				/
Save Path:				/tmp
Use Cookies:				On
Use Only Cookies:			On
FSOCKOPEN:				Your server supports fsockopen.
cURL:					Your server supports cURL.
SOAP Client:				Your server has the SOAP Client enabled.
SUHOSIN:					Your server does not have SUHOSIN installed.
OpenSSL:					Your server has OpenSSL installed.

	** PLUGIN INFORMATION **
Total Plugins: (55)

Must-Use Plugins: (5)
	- cached-nav-menus.php 
	- Force Strong Passwords 1.2.2
	- lb-mu.php 
	- WP Stack CDN 0.3
	- WP Stack CDN Domain Field 1.0

Active Plugins: (50)
	- AA Link Shortcodes 1.0.2
	- Boxzilla 3.0.3
	- CloudFlare 1.3.24
	- Code Snippets 2.6.1
	- FB Save Button for WP 1.0.0
	- GitHub Updater 5.5.0
	- MailChimp for WordPress 3.1.11
	- MailChimp for WordPress - Top Bar 1.2.10
	- MailChimp User Sync 1.4.6
	- NextScripts: Social Networks Auto-Poster 3.6.5
	- Onepager - Advanced Blocks Pack 1.0.0
	- Onepager - One Page Builder 1.2.5
	- Onepager Storefront Support 0.1
	- Sensei 1.9.6
	- Sensei Certificates 1.0.13
	- Sensei Content Drip 1.0.5
	- Sensei Course Participants 1.1.3
	- Sensei Course Progress 1.0.6
	- Sensei Media Attachments 1.0.0
	- Sensei Share Your Grade 1.0.3
	- Shiny Updates 2-20160705
	- Sidebar Login 2.7.3
	- Social Warfare 1.4.8
	- Storefront Blog Customiser 1.2.1
	- Storefront Blog Excerpt 1.1.1
	- Storefront Designer 1.8.3
	- Storefront Footer Bar 1.0.3
	- Storefront Mega Menus 1.3.0
	- Storefront Parallax Hero 1.5.2
	- System Snapshot Report 1.0.2
	- The SEO Framework 2.6.6.2
	- Title Toggle for Storefront Theme 1.2.2
	- User Switching 1.0.9
	- VIP Scanner 0.7
	- Visual Term Description Editor 1.5.0
	- Voice Search 1.2.1
	- WDS Customizer CSS 1.0.0
	- Woo Sensei Analytics 1.2.0
	- Woo Sensei Shortcodes 1.2.0
	- WooThemes Helper 1.6.2
	- WordPress Zero Spam 2.1.1
	- WP-PJAX 0.0.4.1.1
	- WP-Sweep 1.0.7
	- WP Author Box Pro 2.0.7
	- WP Dashboard Notes 1.0.8.2
	- WPDB PHP Sessions 
	- WP Post Series 1.1.0
	- WP Scanner 1.0.2
	- WP Widgets Shortcode 1.0.3
	- Yoast SEO Premium 3.2.5

Inactive Plugins: (0)
```

**Comment by swissspidy** [comment]
Are you running the plugin downloaded from GitHub? I see `github-swissspidy-voice-search` in the source code. `js/voice-search.min.js` isn't available when simply downloading the repository from GitHub. You either need to _build_ the source files using Grunt (`npm install && grunt`) or download the plugin from [WordPress.org](https://wordpress.org/plugins/voice-search/).

In addition to that, I also need to fix #2 in order for the URL to the JavaScript file to be correct. I'll try to publish a 1.2.2 release tomorrow to address this.

**Comment by BurlesonBrad** [comment]
oh dear Lord. You should see this Windows 10 try to cough up VVV and run it. It's a total joke.
Lemme grab it from wp.org :+1:

**Comment by BurlesonBrad** [comment]
installed via wp.org and added the #2 fix as well. https://pressily.com/lesson/serverpress-quick-deploy/
# Good to go! 
#whoop! This is cause for :fireworks: :tada: :balloon: :birthday: :gift: :boom:

**Comment by BurlesonBrad** [comment]
...if only there was a way to fire up that js to automatically **start** the search immediately after the speech recognition realizes that the talking has stopped **without** having to press the mic icon. 

 _think Siri_

**Comment by swissspidy** [comment]
Great to hear it's working now! Love the widget title 🙂

And awesome suggestion, too! That's what I created #5 for after all. See https://twitter.com/swissspidy/status/750799059233935360

**Comment by BurlesonBrad** [comment]
"Hey WordPress, please update my plugins" 
_why isn't there a Homer Simpson "Doh!" emoji?_ 

That's some **over-the-top** functionality @swissspidy 

wait.... What is this fellah usin' here? https://wordpress.org/plugins/speech-to-text/

Ain't that the same library? 
![speech-lib](https://cloud.githubusercontent.com/assets/6208757/16635837/f07840b4-4399-11e6-9e5a-6a64ee58ba19.png)

Oh, wait.... look what I Googled _(seriously not sure if it helps, but **I think** it will)_
``` mySpeechRecognition.stop(); ```
So, after it "stops" it would then trigger the **search**, right?

**Comment by BurlesonBrad** [comment]
I should probably just go back to my WooCommerce and stop now :+1:
